name: GoReleaser

on: push

env:
  REGISTRY: ghcr.io

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
      - name: Checkout freqtrade repository
        uses: actions/checkout@v2
        with:
          repository: freqtrade/freqtrade
          path: freqtrade

      - name: Prepare
        run: |
          DOCKER_IMAGE=${{ github.actor }}/freqtrade_poc
          TAGS="${DOCKER_IMAGE}:${GITHUB_SHA::8}"

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: freqtrade/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest
