name: GoReleaser

on: push

env:
  REGISTRY: ghcr.io

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
      - name: Checkout freqtrade repository
        uses: actions/checkout@v2
        with:
          repository: freqtrade/freqtrade
          path: freqtrade

      - name: Download talib
        run: |
          cd freqtrade
          curl -sLo ta-lib.tar.gz http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvzf ta-lib.tar.gz
          sed -i.bak "s|0.00000001|0.000000000000000001 |g" ta-lib/src/ta_func/ta_utility.h

          curl -sLo ta-lib/config.guess 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'
          curl -sLo ta-lib/config.sub 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: data
        name: Prepare docker data
        run: |
          DOCKER_IMAGE="${REGISTRY}/${{ github.actor }}/freqtrade_poc"
          NAME="${DOCKER_IMAGE}:${GITHUB_SHA::8}"

          echo "$NAME"
          echo ::set-output name=docker_image::${NAME}

          # copy custom dockerfile to freqtrade
          # mv Dockerfile freqtrade/Dockerfile

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: freqtrade
          file: freqtrade/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.data.outputs.docker_image }}
